name: CI Quality Pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Linter (ESLint)
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Gin4ud_SmartInternship
            -Dsonar.organization=smart-internship
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}